In [26]:
from cobra.io import read_sbml_model
from cobra import Reaction, Metabolite

# Read model (model of Escherichia coli)
model_1 = read_sbml_model('iML1515.xml')

In [27]:
model_1.summary()

In [5]:
#model.reactions.DM_4crsol_c
# p-Cresol leaving the system

In [8]:
#model.metabolites.get_by_id('4crsol_c')
# only other reaction is TYRL, so maybe knock that one out?

In [10]:
#model.reactions.DM_5drib_c
# 5'-deoxyribose to leaving the system

In [12]:
#model.reactions.DM_amob_c

In [28]:
model_2 = read_sbml_model('model_atocopherol.xml')

In [29]:
model_2.objective = model.reactions.DM_avite1_c

In [30]:
with model_2:
    model_2.reactions.BIOMASS_Ec_iML1515_core_75p37M.lower_bound = 0.44
    summary = model_2.summary()
summary

In [31]:
model_3 = read_sbml_model('model_atocopherol_tyr.xml')

In [32]:
model_3.objective = model.reactions.DM_avite1_c

In [33]:
with model_3:
    model_3.reactions.BIOMASS_Ec_iML1515_core_75p37M.lower_bound = 0.44
    summary = model_3.summary()
summary